name: Deploy to Digital Ocean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /root/Project/PaddelAppBack/PadelApp/PadelApp
          git pull origin master
          docker build -t padelapp:latest .
          docker stop padelapp-padelapp-1 || true
          docker rm padelapp-padelapp-1 || true
          docker run --name your_container_name -d -p 80:80 padelapp:latest
